project:
  type: website

website:
  title: "Palmer Penguins Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: EDA

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

